# Test against this version of Node.js
environment:
  nodejs_version: "0.12.0"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  # install modules
  - dir C:\Users\appveyor
  - dir C:\Users\appveyor\.node-gyp
  - dir C:\Users\appveyor\.node-gyp\0.12.0
  - dir C:\Users\appveyor\.node-gyp\0.12.0\Debug
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test
